#ifndef CALCULATORCORE_GLOBAL_H
#define CALCULATORCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCULATORCORE_LIBRARY)
#  define CALCULATORCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CALCULATORCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCULATORCORE_GLOBAL_H
